- 💋 Olá, me chamo Maria Eduarda 
- 📋 Atualmente estou trabalhando no mergulhão, como caixa de supermercado.
- 📌 Atualmente estou aprendendo relacionado a informática.
- ✨ Estou procurando colaborar com as aulas, tentando aprender cada dia mais sobre esse ramo de informática, robótica, etc.
- 📫 Meu sonho sempre foi ser pediatra ou nutricionista, mas requer muito estudo, estoui pensando sobre. Mas minha terceira opção seria Arquiteta, sempre me interessei muito em projetos, ainda mais quando se trata de casas, requer um esforço muito grande também.
- 😄 Pronouns: Ela/dela
- 😺 41 99276-0830
